export const builderTabs = [
  {
    id: "research",
    label: "Research",
    kicker: "Signal cluster",
    title: "Continuity breaks between sessions",
    body: "The retention drop is concentrated among users who complete a first conversation but do not reach a meaningful exchange in session two.",
    lines: ["Cohort / newly activated", "Window / days 2 to 4", "Signal / cold re-entry", "Unknown / cause vs. correlation"],
  },
  {
    id: "spec",
    label: "Frame",
    kicker: "Falsifiable framing",
    title: "Returning does not feel valuable yet",
    body: "New users are not consistently establishing enough conversational continuity to make returning feel valuable.",
    lines: ["Not / improve retention", "Behaviour / second-session depth", "Uncertainty / continuity", "Constraint / user control"],
  },
  {
    id: "prototype",
    label: "Prototype",
    kicker: "Smallest meaningful version",
    title: "Resume with approved context",
    body: "At session two, offer a short user-editable memory summary, then use it to continue one unresolved conversational thread.",
    lines: ["State / summary offered", "Action / review or edit", "System / resume context", "Fallback / start fresh"],
  },
  {
    id: "code",
    label: "Code",
    kicker: "Inspectable behaviour",
    title: "Instrument the assumption",
    body: "The prototype becomes useful when the state and evidence are concrete enough for design and engineering to challenge.",
    code: `track("companion_session_continued", {\n  cohort,\n  session_number,\n  memory_used,\n  response_latency,\n  conversation_depth\n});`,
  },
  {
    id: "events",
    label: "Events",
    kicker: "Decision plumbing",
    title: "Connect behaviour to a decision",
    body: "Event → user property → cohort → metric → decision. Names are illustrative; the structure is the point.",
    lines: ["Event / conversation_resumed", "Property / memory_used", "Cohort / activated <7d", "Metric / meaningful return rate"],
  },
  {
    id: "experiment",
    label: "Decision",
    kicker: "Pre-committed rule",
    title: "Scale only when the system passes",
    body: "Primary behaviour must improve while safety, latency and economic guardrails remain inside tolerance.",
    code: `const decision =\n  primaryMetric > threshold &&\n  safetyGuardrails.every(g => g.passed)\n    ? "scale"\n    : "iterate";`,
  },
];
